services:
  nginxproxymanager:
    container_name: reverse_proxy
    image: jlesage/nginx-proxy-manager
    ports:
      - 8181:7818
      - 80:80
      - 443:443
    volumes:
      - ./config:/config