services:
  dashboard:
    container_name: dashboard
    image: ghcr.io/gethomepage/homepage
    ports:
      - 3000:3000
      - 22:2222
    volumes:
      - ./icons:/app/public/icons
      - ./images:/app/public/images
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
      - /drive1:/drive1
      - /drive2:/drive2
      - /drive3:/drive3
      